# Generated by Django 3.0.5 on 2020-12-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Holiday_Choice', models.CharField(choices=[('CHD', 'Christmas Day'), ('NYD', 'New Year'), ('CAD', 'Canada Day'), ('THG', 'Thanksgiving'), ('OTH', 'Other')], default='Christmas Day', max_length=3)),
                ('Recipient_Name', models.CharField(max_length=40)),
                ('Recipient_Location', models.CharField(max_length=40)),
                ('Short_Message', models.TextField(max_length=200)),
                ('Your_Name', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
