# Generated by Django 3.0.5 on 2020-12-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinfo',
            name='Machine_Learning_Generated_Message',
            field=models.BooleanField(default=False),
        ),
    ]
