# Generated by Django 3.0.5 on 2020-12-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20201227_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='Holiday_Choice',
            field=models.CharField(choices=[('CHD', 'Christmas Day'), ('NYD', 'New Year'), ('VTD', 'Valentines Day'), ('CAD', 'Canada Day'), ('THG', 'Thanksgiving'), ('OTH', 'Other')], default='Christmas Day', max_length=3),
        ),
    ]
